# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod.Dockerfile

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
