name: Test Contract Code 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['release', 'develop']

  pull_request:
    branches: ['release', 'develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Dummy vars
        run: npx hardhat vars set INFURA_API_KEY '' && \
             npx hardhat vars set SEPOLIA_PRIVATE_KEY '' 
      - name: Test
        run: npm run test
